# -*- coding: utf-8 -*-
"""_sandbox_

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v-tFd5BiZ_W8JxZ_-n_z4VCLynZeMT-L
"""

js_code = '''(function(_0x2a0650, _0x28a91e) {
    const _0xd45308 = _0x3a8d
      , _0x4955cd = _0x2a0650();
    while (!![]) {
        try {
            const _0x2eca83 = parseInt(_0xd45308(0x10a)) / 0x1 * (parseInt(_0xd45308(0x113)) / 0x2) + -parseInt(_0xd45308(0x10d)) / 0x3 * (parseInt(_0xd45308(0x116)) / 0x4) + -parseInt(_0xd45308(0x10c)) / 0x5 * (-parseInt(_0xd45308(0x11b)) / 0x6) + parseInt(_0xd45308(0x123)) / 0x7 + parseInt(_0xd45308(0x11a)) / 0x8 + parseInt(_0xd45308(0x125)) / 0x9 + -parseInt(_0xd45308(0x11d)) / 0xa;
            if (_0x2eca83 === _0x28a91e)
                break;
            else
                _0x4955cd['push'](_0x4955cd['shift']());
        } catch (_0x1d75b5) {
            _0x4955cd['push'](_0x4955cd['shift']());
        }
    }
}(_0x54b9, 0x20892));
function _0x3a8d(_0x526f3f, _0x5658cb) {
    const _0x54b945 = _0x54b9();
    return _0x3a8d = function(_0x3a8df2, _0x3afa42) {
        _0x3a8df2 = _0x3a8df2 - 0x10a;
        let _0x2ea32b = _0x54b945[_0x3a8df2];
        return _0x2ea32b;
    }
    ,
    _0x3a8d(_0x526f3f, _0x5658cb);
}
function _0x54b9() {
    const _0x1d5de3 = ['join', '1766601DKvkfN', '39aXORCP', 'toUpperCase', '87280owbbkp', '6AzawBg', 'fromCharCode', 'toString', 'splice', 'mg3c3b04ba', 'substr', '9634ttJadP', 'length', 'referrer', '499416bEetdB', 'platform', 'appCodeName', 'navigator', '359664FzBQCJ', '12yJxJzi', 'userAgent', '1065160icGOUk', 'toLowerCase', 'document', 'push', 'charCodeAt', 'undefined', '178276lBUtOp'];
    _0x54b9 = function() {
        return _0x1d5de3;
    }
    ;
    return _0x54b9();
}
var _0x54b991 = (function() {
    function _0x1b25b9(_0x3378d3) {
        const _0xb4c3 = _0x3a8d
          , _0x186fc8 = _0x3378d3[_0xb4c3(0x114)]
          , _0x5ac8cf = [];
        for (let _0x2ccc5f = 0x0; _0x2ccc5f < _0x186fc8; _0x2ccc5f++)
            _0x5ac8cf[_0x2ccc5f >>> 0x2] |= (0xff & _0x3378d3[_0xb4c3(0x121)](_0x2ccc5f)) << 0x18 - _0x2ccc5f % 0x4 * 0x8;
        return [_0x5ac8cf, _0x186fc8];
    }
    function _0x1c779c(_0x3ff981, _0x459037) {
        const _0x32cb7c = _0x3a8d
          , _0x220b47 = [];
        for (let _0x44ccb3 = 0x0; _0x44ccb3 < _0x459037; _0x44ccb3++) {
            _0x220b47[_0x32cb7c(0x120)]((_0x3ff981[_0x44ccb3 >>> 0x2] >>> 0x18 - _0x44ccb3 % 0x4 * 0x8 & 0xff)[_0x32cb7c(0x10f)](0x10)['padStart'](0x2, '0'));
        }
        return _0x220b47[_0x32cb7c(0x124)]('');
    }
    function _0x12af79(_0x4dcec4) {
        const _0x3c28b6 = _0x3a8d;
        return (_0x4dcec4 || '')[_0x3c28b6(0x112)](0x0, 0x30);
    }
    function _0x70dbf4(_0x524c4a) {
        const _0x1d3496 = _0x3a8d;
        let _0x109c6f = 0x0;
        const _0x5ebb16 = _0x524c4a[_0x1d3496(0x114)];
        for (let _0x419dc5 = 0x0; _0x419dc5 < _0x5ebb16; _0x419dc5++)
            _0x109c6f = (_0x109c6f << 0x5) - _0x109c6f + _0x524c4a[_0x1d3496(0x121)](_0x419dc5);
        return _0x109c6f;
    }
    function _0x29e11d(_0x4440b3) {
        const _0x25677b = _0x3a8d
          , _0x384f5f = 0x10 - _0x4440b3[_0x25677b(0x114)] % 0x10;
        for (let _0x120ea8 = 0x0; _0x120ea8 < _0x384f5f; ++_0x120ea8)
            _0x4440b3 += String[_0x25677b(0x10e)](_0x384f5f);
        return _0x4440b3;
    }
    function _0xaf4f42(_0x1493a6) {
        const _0x3815a4 = _0x3a8d
          , _0x5c4ece = _0x1493a6[_0x3815a4(0x114)];
        for (let _0x3835b2 = 0x0; _0x3835b2 < _0x5c4ece; _0x3835b2 += 0x4)
            _0x3505d7(_0x1493a6, _0x3835b2);
    }
    const _0x6b7b62 = [[0x4f6bdaa3, -0x61d07350, 0x7f5e722d, -0x61210cec, 0x536620a8, -0x32b653e8, -0x4de821cb, 0x2cc92d21, -0x73412227, 0x41f771c1, -0xc1f500c, -0x20d67d2b, 0x2dadde47, 0x6c5aaf86, -0x6045ff8e, 0x409382a7, -0x6417db2, -0x6a1bd238, 0xa5e2dba, 0x4acdaf1d, 0x54c72698, -0x3edcf4b0, -0x3482d916, -0x7e4f7609, -0x6c9fb16c, 0x524345c4, -0x66c19cd2, 0x188eead9, -0x351884c7, -0x675bc103, 0x19a5dd3, 0x1914b70a, -0x4fb1e313, 0x28ea2210, 0x29707fc3, 0x3064c8c9, -0x17593e17, -0x3fb31c07, -0x16c363c6, -0x26a7ab0d, -0x4b793324, 0x74ca2f25, -0x62094ce1, 0x44aee7ec]];
    (function() {
        const _0x52fed1 = _0x3a8d;
        var _0x43be17 = []
          , _0x42a74d = []
          , _0xb4bd43 = []
          , _0x25f5e6 = []
          , _0x5d5f77 = []
          , _0x2de806 = [];
        for (let _0x21abca = 0x0; _0x21abca < 0x100; _0x21abca++)
            _0x2de806[_0x21abca] = _0x21abca < 0x80 ? _0x21abca << 0x1 : _0x21abca << 0x1 ^ 0x11b;
        var _0x2119ec = 0x0
          , _0x1a0508 = 0x0;
        for (let _0x11eabb = 0x0; _0x11eabb < 0x100; _0x11eabb++) {
            var _0x5034cc = _0x1a0508 ^ _0x1a0508 << 0x1 ^ _0x1a0508 << 0x2 ^ _0x1a0508 << 0x3 ^ _0x1a0508 << 0x4;
            _0x5034cc = _0x5034cc >>> 0x8 ^ 0xff & _0x5034cc ^ 0x63,
            _0x43be17[_0x2119ec] = _0x5034cc;
            var _0x580af8 = _0x2de806[_0x2119ec]
              , _0x354320 = _0x2de806[_0x2de806[_0x580af8]]
              , _0x410b1f = 0x101 * _0x2de806[_0x5034cc] ^ 0x1010100 * _0x5034cc;
            _0x42a74d[_0x2119ec] = _0x410b1f << 0x18 | _0x410b1f >>> 0x8,
            _0xb4bd43[_0x2119ec] = _0x410b1f << 0x10 | _0x410b1f >>> 0x10,
            _0x25f5e6[_0x2119ec] = _0x410b1f << 0x8 | _0x410b1f >>> 0x18,
            _0x5d5f77[_0x2119ec] = _0x410b1f,
            _0x2119ec ? (_0x2119ec = _0x580af8 ^ _0x2de806[_0x2de806[_0x2de806[_0x354320 ^ _0x580af8]]],
            _0x1a0508 ^= _0x2de806[_0x2de806[_0x1a0508]]) : _0x2119ec = _0x1a0508 = 0x1;
        }
        _0x6b7b62['push'](_0x42a74d),
        _0x6b7b62[_0x52fed1(0x120)](_0xb4bd43),
        _0x6b7b62[_0x52fed1(0x120)](_0x25f5e6),
        _0x6b7b62['push'](_0x5d5f77),
        _0x6b7b62[_0x52fed1(0x120)](_0x43be17);
    }());
    function _0x3505d7(_0x13a508, _0x5baaa1) {
        const [_0x458390,_0x32aa26,_0x53dadc,_0x4810d1,_0x3c0f1b,_0x128bff] = _0x6b7b62;
        let _0x21ba3f;
        _0x5baaa1 === 0x0 ? _0x21ba3f = [0x1504af3, 0x56e619cf, 0x2e42bba6, -0x73c08f07] : _0x21ba3f = _0x13a508['slice'](_0x5baaa1 - 0x4, _0x5baaa1);
        for (let _0x5b9637 = 0x0; _0x5b9637 < 0x4; _0x5b9637++)
            _0x13a508[_0x5baaa1 + _0x5b9637] ^= _0x21ba3f[_0x5b9637];
        for (var _0x116405 = 0xa, _0x4d3231 = _0x13a508[_0x5baaa1] ^ _0x458390[0x0], _0x1f3a4f = _0x13a508[_0x5baaa1 + 0x1] ^ _0x458390[0x1], _0x598b52 = _0x13a508[_0x5baaa1 + 0x2] ^ _0x458390[0x2], _0x2265d4 = _0x13a508[_0x5baaa1 + 0x3] ^ _0x458390[0x3], _0xcb5ec5 = 0x4, _0x5e2dc7 = 0x1; _0x5e2dc7 < _0x116405; _0x5e2dc7++) {
            var _0x34de78 = _0x32aa26[_0x4d3231 >>> 0x18] ^ _0x53dadc[_0x1f3a4f >>> 0x10 & 0xff] ^ _0x4810d1[_0x598b52 >>> 0x8 & 0xff] ^ _0x3c0f1b[0xff & _0x2265d4] ^ _0x458390[_0xcb5ec5++]
              , _0x42d7a0 = _0x32aa26[_0x1f3a4f >>> 0x18] ^ _0x53dadc[_0x598b52 >>> 0x10 & 0xff] ^ _0x4810d1[_0x2265d4 >>> 0x8 & 0xff] ^ _0x3c0f1b[0xff & _0x4d3231] ^ _0x458390[_0xcb5ec5++]
              , _0x4a8c71 = _0x32aa26[_0x598b52 >>> 0x18] ^ _0x53dadc[_0x2265d4 >>> 0x10 & 0xff] ^ _0x4810d1[_0x4d3231 >>> 0x8 & 0xff] ^ _0x3c0f1b[0xff & _0x1f3a4f] ^ _0x458390[_0xcb5ec5++];
            _0x2265d4 = _0x32aa26[_0x2265d4 >>> 0x18] ^ _0x53dadc[_0x4d3231 >>> 0x10 & 0xff] ^ _0x4810d1[_0x1f3a4f >>> 0x8 & 0xff] ^ _0x3c0f1b[0xff & _0x598b52] ^ _0x458390[_0xcb5ec5++],
            _0x4d3231 = _0x34de78,
            _0x1f3a4f = _0x42d7a0,
            _0x598b52 = _0x4a8c71;
        }
        _0x34de78 = (_0x128bff[_0x4d3231 >>> 0x18] << 0x18 | _0x128bff[_0x1f3a4f >>> 0x10 & 0xff] << 0x10 | _0x128bff[_0x598b52 >>> 0x8 & 0xff] << 0x8 | _0x128bff[0xff & _0x2265d4]) ^ _0x458390[_0xcb5ec5++],
        _0x42d7a0 = (_0x128bff[_0x1f3a4f >>> 0x18] << 0x18 | _0x128bff[_0x598b52 >>> 0x10 & 0xff] << 0x10 | _0x128bff[_0x2265d4 >>> 0x8 & 0xff] << 0x8 | _0x128bff[0xff & _0x4d3231]) ^ _0x458390[_0xcb5ec5++],
        _0x4a8c71 = (_0x128bff[_0x598b52 >>> 0x18] << 0x18 | _0x128bff[_0x2265d4 >>> 0x10 & 0xff] << 0x10 | _0x128bff[_0x4d3231 >>> 0x8 & 0xff] << 0x8 | _0x128bff[0xff & _0x1f3a4f]) ^ _0x458390[_0xcb5ec5++],
        _0x2265d4 = (_0x128bff[_0x2265d4 >>> 0x18] << 0x18 | _0x128bff[_0x4d3231 >>> 0x10 & 0xff] << 0x10 | _0x128bff[_0x1f3a4f >>> 0x8 & 0xff] << 0x8 | _0x128bff[0xff & _0x598b52]) ^ _0x458390[_0xcb5ec5++],
        _0x13a508[_0x5baaa1] = _0x34de78,
        _0x13a508[_0x5baaa1 + 0x1] = _0x42d7a0,
        _0x13a508[_0x5baaa1 + 0x2] = _0x4a8c71,
        _0x13a508[_0x5baaa1 + 0x3] = _0x2265d4;
    }
    return function(_0x3be93d, _0x3e48ea, _0xbf2c16, _0x576527, _0x454b79, _0x361753, _0x3cdffa, _0x2fa7de, _0xdaf7bd, _0x59e242, _0x5674ce) {
        const _0x5acc2f = _0x3a8d;
        if (typeof _0x361753 === _0x5acc2f(0x122))
            _0x361753 = window[_0x5acc2f(0x11f)]['URL'];
        if (typeof _0x3cdffa === _0x5acc2f(0x122))
            _0x3cdffa = window[_0x5acc2f(0x119)][_0x5acc2f(0x11c)];
        if (typeof _0x2fa7de === _0x5acc2f(0x122))
            _0x2fa7de = window[_0x5acc2f(0x11f)][_0x5acc2f(0x115)];
        if (typeof _0xdaf7bd === _0x5acc2f(0x122))
            _0xdaf7bd = window[_0x5acc2f(0x119)][_0x5acc2f(0x118)];
        if (typeof _0x59e242 === _0x5acc2f(0x122))
            _0x59e242 = window[_0x5acc2f(0x119)]['appName'];
        if (typeof _0x5674ce === _0x5acc2f(0x122))
            _0x5674ce = window[_0x5acc2f(0x119)][_0x5acc2f(0x117)];
        const _0x5989e7 = ['', _0x3be93d, _0x3e48ea, _0x5acc2f(0x111), _0xbf2c16, _0x576527, _0x454b79, _0x12af79(_0x361753), _0x12af79(_0x3cdffa[_0x5acc2f(0x11e)]()), _0x12af79(_0x2fa7de), _0xdaf7bd, _0x59e242, _0x5674ce, '00', ''];
        _0x5989e7[_0x5acc2f(0x110)](0x1, 0x0, _0x70dbf4(_0x5989e7[_0x5acc2f(0x124)]('|')));
        const _0x278f64 = _0x29e11d(_0x5989e7[_0x5acc2f(0x124)]('|'))
          , [_0x3db385,_0x2f9d88] = _0x1b25b9(_0x278f64);
        return _0xaf4f42(_0x3db385),
        _0x1c779c(_0x3db385, _0x2f9d88)[_0x5acc2f(0x10b)]();
    }
    ;
}());

// input
_0x54b991(173287, null, "2.8.10", "62f176f3bb1b5b8e70e39932ad34a0c7", 4830201,  "kisskh", "kisskh", "kisskh", "kisskh", "kisskh", "kisskh")'''

# Commented out IPython magic to ensure Python compatibility.
# %pip install js2py

!pip install py_mini_racer
import py_mini_racer

ctx = py_mini_racer.MiniRacer()
res_2 = ctx.eval(js_code)  # Assuming js_code contains your JavaScript
print(res_2)

!pip install quickjs
import quickjs

ctx = quickjs.Context()
res_2 = ctx.eval(js_code)
print(res_2)

!pip install jsbeautifier
import jsbeautifier as js
js.beautify(js_code)

function getVal(p, a, c, k, e, d) { e = function (c) { return (c < a ? '' : e(parseInt(c / a))) + ((c = c % a) > 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!''.replace(/^/, String)) { while (c--) { d[e(c)] = k[c] || e(c) } k = [function (e) { return d[e] }]; e = function () { return '\\w+' }; c = 1 }; while (c--) { if (k[c]) { p = p.replace(new RegExp('\\b' + e(c) + '\\b', 'g'), k[c]) } } return p }

getVal('j q=\'1N://1M-12.1L.1K/1J/12/1I/1H/1G.1F\';j g=u.t(\'g\');j 3=D 1E(g,{\'1D\':{\'1C\':k},\'1B\':\'16:9\',\'G\':1,\'1A\':5,\'1z\':{1y:1,1x:[0.1w,1,1.1,1.15,1.2,1.1v,1.5,2,4]},\'1u\':{\'1t\':\'1s\'},\'1r\':[\'a-1q\',\'a\',\'1p\',\'1o-1n\',\'1m\',\'1l-1k\',\'1j\',\'G\',\'1i\',\'1h\',\'1g\',\'1f\',\'F\',\'1e\'],\'F\':{\'1d\':k}});b(!C.1c()){g.1b=q}z{l B={1a:19,18:17*E*E,14:13,11:10,Z:9,Y:k,X:k};j f=D C(B);f.W(q);f.V(g);i.f=f}3.6("U",8=>{i.T.S.R("Q")});m x(d,p,o){b(d.A){d.A(p,o,P)}z b(d.y){d.y(\'6\'+p,o)}}l 7=m(n){i.O.N(n,\'*\')};x(i,\'n\',m(e){l c=e.c;b(c===\'a\')3.a();b(c===\'h\')3.h();b(c===\'w\')3.w()});3.6(\'v\',8=>{7(\'v\')});3.6(\'a\',8=>{7(\'a\')});3.6(\'h\',8=>{7(\'h\')});3.6(\'M\',8=>{7(3.s);u.t(\'.L-K\').J=I(3.s.H(2))});3.6(\'r\',8=>{7(\'r\')});', 62, 112, '|||player|||on|sendMessage|event||play|if|data|element||hls|video|pause|window|const|true|var|function|message|eventHandler|eventName|source|ended|currentTime|querySelector|document|ready|stop|bindEvent|attachEvent|else|addEventListener|config|Hls|new|1000|fullscreen|volume|toFixed|String|innerHTML|timestamp|ss|timeupdate|postMessage|parent|false|landscape|lock|orientation|screen|enterfullscreen|attachMedia|loadSource|lowLatencyMode|enableWorker|nudgeMaxRetry|600|maxMaxBufferLength||300|maxBufferLength|||120|maxBufferSize|90|backBufferLength|src|isSupported|iosNative|capture|airplay|pip|settings|captions|mute|time|current|progress|forward|fast|rewind|large|controls|kwik|key|storage|25|75|options|selected|speed|seekTime|ratio|global|keyboard|Plyr|m3u8|uwu|52db810955959547e19689b09f8ae143bcac6ebcf6cbac378d5ef6fc28c0edb0|01|stream|ru|kwikie|vault|https'.split('|'), 0, {})

;eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('j q=\'1N://1M-H.1L.1K/1J/H/1I/1H/1G.1F\';j g=u.t(\'g\');j 3=D 1E(g,{\'1D\':{\'1C\':k},\'1B\':\'16:9\',\'G\':1,\'1A\':5,\'1z\':{1y:1,1x:[0.1w,1,1.1,1.15,1.2,1.1v,1.5,2,4]},\'1u\':{\'1t\':\'1s\'},\'1r\':[\'a-1q\',\'a\',\'1p\',\'1o-1n\',\'1m\',\'1l-1k\',\'1j\',\'G\',\'1i\',\'1h\',\'1g\',\'1f\',\'F\',\'1e\'],\'F\':{\'1d\':k}});b(!C.1c()){g.1b=q}z{l B={1a:19,18:17*E*E,14:13,12:11,10:9,Z:k,Y:k};j f=D C(B);f.X(q);f.W(g);i.f=f}3.6("V",8=>{i.U.T.S("R")});m x(d,p,o){b(d.A){d.A(p,o,Q)}z b(d.y){d.y(\'6\'+p,o)}}l 7=m(n){i.P.O(n,\'*\')};x(i,\'n\',m(e){l c=e.c;b(c===\'a\')3.a();b(c===\'h\')3.h();b(c===\'w\')3.w()});3.6(\'v\',8=>{7(\'v\')});3.6(\'a\',8=>{7(\'a\')});3.6(\'h\',8=>{7(\'h\')});3.6(\'N\',8=>{7(3.s);u.t(\'.M-L\').K=J(3.s.I(2))});3.6(\'r\',8=>{7(\'r\')});',62,112,'|||player|||on|sendMessage|event||play|if|data|element||hls|video|pause|window|const|true|var|function|message|eventHandler|eventName|source|ended|currentTime|querySelector|document|ready|stop|bindEvent|attachEvent|else|addEventListener|config|Hls|new|1000|fullscreen|volume|99|toFixed|String|innerHTML|timestamp|ss|timeupdate|postMessage|parent|false|landscape|lock|orientation|screen|enterfullscreen|attachMedia|loadSource|lowLatencyMode|enableWorker|nudgeMaxRetry|600|maxMaxBufferLength|300|maxBufferLength|||120|maxBufferSize|90|backBufferLength|src|isSupported|iosNative|capture|airplay|pip|settings|captions|mute|time|current|progress|forward|fast|rewind|large|controls|kwik|key|storage|25|75|options|selected|speed|seekTime|ratio|global|keyboard|Plyr|m3u8|uwu|9e027cb2d63ad6e9744cf15b53eb2f695d46d662ee60349013753158abcc4f76|01|stream|ru|kwikie|vault|https'.split('|'),0,{}))

;eval(function(p,a,c,k,e,d){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--){d[e(c)]=k[c]||e(c)}k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1};while(c--){if(k[c]){p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c])}}return p}('j q=\'1N://1M-12.1L.1K/1J/12/1I/1H/1G.1F\';j g=u.t(\'g\');j 3=D 1E(g,{\'1D\':{\'1C\':k},\'1B\':\'16:9\',\'G\':1,\'1A\':5,\'1z\':{1y:1,1x:[0.1w,1,1.1,1.15,1.2,1.1v,1.5,2,4]},\'1u\':{\'1t\':\'1s\'},\'1r\':[\'a-1q\',\'a\',\'1p\',\'1o-1n\',\'1m\',\'1l-1k\',\'1j\',\'G\',\'1i\',\'1h\',\'1g\',\'1f\',\'F\',\'1e\'],\'F\':{\'1d\':k}});b(!C.1c()){g.1b=q}z{l B={1a:19,18:17*E*E,14:13,11:10,Z:9,Y:k,X:k};j f=D C(B);f.W(q);f.V(g);i.f=f}3.6("U",8=>{i.T.S.R("Q")});m x(d,p,o){b(d.A){d.A(p,o,P)}z b(d.y){d.y(\'6\'+p,o)}}l 7=m(n){i.O.N(n,\'*\')};x(i,\'n\',m(e){l c=e.c;b(c===\'a\')3.a();b(c===\'h\')3.h();b(c===\'w\')3.w()});3.6(\'v\',8=>{7(\'v\')});3.6(\'a\',8=>{7(\'a\')});3.6(\'h\',8=>{7(\'h\')});3.6(\'M\',8=>{7(3.s);u.t(\'.L-K\').J=I(3.s.H(2))});3.6(\'r\',8=>{7(\'r\')});',62,112,'|||player|||on|sendMessage|event||play|if|data|element||hls|video|pause|window|const|true|var|function|message|eventHandler|eventName|source|ended|currentTime|querySelector|document|ready|stop|bindEvent|attachEvent|else|addEventListener|config|Hls|new|1000|fullscreen|volume|toFixed|String|innerHTML|timestamp|ss|timeupdate|postMessage|parent|false|landscape|lock|orientation|screen|enterfullscreen|attachMedia|loadSource|lowLatencyMode|enableWorker|nudgeMaxRetry|600|maxMaxBufferLength||300|maxBufferLength|||120|maxBufferSize|90|backBufferLength|src|isSupported|iosNative|capture|airplay|pip|settings|captions|mute|time|current|progress|forward|fast|rewind|large|controls|kwik|key|storage|25|75|options|selected|speed|seekTime|ratio|global|keyboard|Plyr|m3u8|uwu|52db810955959547e19689b09f8ae143bcac6ebcf6cbac378d5ef6fc28c0edb0|01|stream|ru|kwikie|vault|https'.split('|'),0,{}))